# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qdivzero < Formula
  desc "Command-line client for the QDivZero API"
  homepage "https://github.com/QDivZero/qdivzero-cli"
  version "1.0.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/QDivZero/qdivzero-cli/releases/download/v1.0.3/qdivzero_1.0.3_darwin_amd64.tar.gz"
      sha256 "4a3ab4d12960af3bd87374fcfdf10eebb17c40ae347785284a1f4e446c19b946"

      define_method(:install) do
        bin.install "qdivzero"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/QDivZero/qdivzero-cli/releases/download/v1.0.3/qdivzero_1.0.3_darwin_arm64.tar.gz"
      sha256 "04625ae2222da6efad364fbf8219b6a365bb6181f1724ce315434dd7e7d89dba"

      define_method(:install) do
        bin.install "qdivzero"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/QDivZero/qdivzero-cli/releases/download/v1.0.3/qdivzero_1.0.3_linux_amd64.tar.gz"
      sha256 "89494a684b29afac4409ffbcdc4253ead2e5600d07972e7f858011afd4939b8b"
      define_method(:install) do
        bin.install "qdivzero"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/QDivZero/qdivzero-cli/releases/download/v1.0.3/qdivzero_1.0.3_linux_arm64.tar.gz"
      sha256 "8c4582377dde97c685438eabdf2a720e6eafcc66d86e45fb291cac26429d5b90"
      define_method(:install) do
        bin.install "qdivzero"
      end
    end
  end

  test do
    system "#{bin}/qdivzero", "version"
  end
end
