# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Qdivzero < Formula
  desc "Command-line client for the QDivZero API"
  homepage "https://github.com/QDivZero/qdivzero-cli"
  version "1.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/QDivZero/qdivzero-cli/releases/download/v1.0.5/qdivzero_1.0.5_darwin_amd64.tar.gz"
      sha256 "7cabe3286405948f0c98c6b4c1e30037dc1ca9e01ede5bf3aab0d721edf6772b"

      define_method(:install) do
        bin.install "qdivzero"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/QDivZero/qdivzero-cli/releases/download/v1.0.5/qdivzero_1.0.5_darwin_arm64.tar.gz"
      sha256 "bc547913defce87bd61e19043f6b723eb7cd22b64195511262e28919b10c9cfa"

      define_method(:install) do
        bin.install "qdivzero"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/QDivZero/qdivzero-cli/releases/download/v1.0.5/qdivzero_1.0.5_linux_amd64.tar.gz"
      sha256 "a1f6b85db532209e7f187965b597ab2883d6f06e4c07167bade0bb7a03f3eb81"
      define_method(:install) do
        bin.install "qdivzero"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/QDivZero/qdivzero-cli/releases/download/v1.0.5/qdivzero_1.0.5_linux_arm64.tar.gz"
      sha256 "376959d2b15ce86047020ac9ea2a7dac9228fd53ac6d238a0b0473df9dca2715"
      define_method(:install) do
        bin.install "qdivzero"
      end
    end
  end

  test do
    system "#{bin}/qdivzero", "version"
  end
end
